"""empty message

Revision ID: 28282f7bd674
Revises: d7d8277bb947
Create Date: 2024-01-09 16:45:56.386981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28282f7bd674'
down_revision = 'd7d8277bb947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='file_pkey')
    )
    op.drop_table('cars')
    # ### end Alembic commands ###
