"""Add size columns to files table

Revision ID: ba7d724bb3dc
Revises: cf9bf57a2254
Create Date: 2025-12-10 21:47:02.752674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7d724bb3dc'
down_revision = 'cf9bf57a2254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_size', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('compressed_size', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('compression_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quality', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('quality')
        batch_op.drop_column('compression_ratio')
        batch_op.drop_column('compressed_size')
        batch_op.drop_column('original_size')

    # ### end Alembic commands ###
